website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, SignUpForm, PasswordForm, ProfileForm
from .models import Customer
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():
        email = form.email.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        password1 = form.password1.data
        password2 = form.password2.data

        if password1 == password2:
            # Check if the email already exists
            existing_customer = Customer.query.filter_by(email=email).first()
            if existing_customer:
                flash(
                    "Email already exists. Please log in or use a different email.",
                    "danger",
                )
                return redirect(url_for("auth.sign_up"))

            new_customer = Customer(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=password1,  # Password hashing is handled by the setter method
            )

            try:
                db.session.add(new_customer)
                db.session.commit()
                flash("Successfully signed up!", "success")
                return redirect(url_for("auth.login"))
            except Exception as e:
                print(e)
                db.session.rollback()
                flash("Account could not be created due to an error.", "danger")
                # Optional: Clear form data on error
                form.email.data = ""
                form.first_name.data = ""
                form.last_name.data = ""
                form.password1.data = ""
                form.password2.data = ""
        else:
            flash("Passwords do not match", "danger")
    return render_template("signup.html", form=form)


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        customer = Customer.query.filter_by(email=email).first()

        if customer:
            if customer.verify_password(password=password):
                login_user(customer)
                return redirect("/")
            else:
                flash("Incorrect Email or Password")

        else:
            flash("Account doew not exist please Sign Up")

    return render_template("login.html", form=form)


@auth.route("/logout", methods=["GET", "POST"])
@login_required
def log_out():
    logout_user()
    return redirect("/")


@auth.route("/profile/<int:customer_id>", methods=["GET", "POST"])
@login_required
def profile(customer_id):
    customer = Customer.query.get(customer_id)
    print("Customer ID:", customer_id)

    if customer.id != current_user.id:
        return redirect(url_for("views.home"))

    profile_form = ProfileForm(obj=customer)
    password_form = PasswordForm()

    if profile_form.submit_profile.data and profile_form.validate_on_submit():
        if (
            Customer.query.filter_by(email=profile_form.email.data).first()
            and profile_form.email.data != customer.email
        ):
            flash("Email already exists", "info_error")
        elif (
            Customer.query.filter_by(
                first_name=profile_form.first_name.data,
                last_name=profile_form.last_name.data,
            ).first()
            and profile_form.first_name.data != customer.first_name
            and profile_form.last_name.data != customer.last_name
        ):
            flash("Name already exists", "info_error")
        else:
            customer.first_name = profile_form.first_name.data
            customer.last_name = profile_form.last_name.data
            customer.email = profile_form.email.data
            customer.phone_number = profile_form.phone_number.data
            customer.address = profile_form.address.data
            db.session.commit()
            flash("Profile updated successfully", "info_success")
        return redirect(url_for("auth.profile", customer_id=customer.id))

    if password_form.submit_password.data and password_form.validate_on_submit():
        if customer.verify_password(password_form.current_password.data):
            customer.password = password_form.new_password.data
            db.session.commit()
            flash("Password updated successfully", "password_success")
        else:
            flash("Current password is incorrect", "password_error")
        return redirect(url_for("auth.profile", customer_id=customer.id))

    return render_template(
        "profile.html",
        customer=customer,
        profile_form=profile_form,
        password_form=password_form,
    )

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
        referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    <link rel="stylesheet" href="/tailwind.config.js">
    <link rel="stylesheet" href="../static/css/tailwind.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="path/to/your/tailwind.css" rel="stylesheet">
    <title>Real Estate | {% block title %} {% endblock %}</title>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        clifford: '#D6D0D0',
                        navbar: '091638'
                    }
                }
            }
        }
    </script>
</head>

<body class="">
    <!-- NAVBAR  -->
    <nav class="bg-navbar z-50 relative">
        <section class="bg-blue-900 font-mulish hidden sm:block max-w-7xl mx-auto">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex justify-between h-16">
                    <div class="flex items-center">
                        <div class="flex-shrink-0 flex items-center">
                            <span class="text-xl font-bold text-white font-mulish">Follow Us</span>
                        </div>
                        <div class="flex ml-4 space-x-4 items-center">
                            <a href="#" class="text-white hover:text-gray-300">
                                <i class="fab fa-facebook-f w-5 h-5"></i>
                            </a>
                            <a href="#" class="text-white hover:text-gray-300">
                                <i class="fab fa-twitter w-5 h-5"></i>
                            </a>
                            <a href="#" class="text-white hover:text-gray-300">
                                <i class="fab fa-instagram w-5 h-5"></i>
                            </a>
                            <a href="#" class="text-white hover:text-gray-300">
                                <i class="fab fa-linkedin-in w-5 h-5"></i>
                            </a>
                        </div>
                    </div>
                    <div class="flex items-center">
                        <div class="ml-4 flex items-center text-white">
                            <a href="#" class="text-white hover:text-gray-300">
                                <i class="fas fa-phone w-4 h-4"></i>
                            </a>
                            <a href="tel:+1234567890" class="ml-2 text-white hover:underline text-sm">+121 685
                                886602</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div
                class="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 relative py-4 flex justify-between items-center bg-[#F3F3FA]">
                <a class="text-3xl font-bold leading-none" href="#">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo">
                </a>
                <div class="lg:hidden">
                    <button class="navbar-burger flex items-center text-blue-600 p-3">
                        <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <title>Mobile menu</title>
                            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
                        </svg>
                    </button>
                </div>
                <ul
                    class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:mx-auto lg:items-center lg:w-auto lg:space-x-6">
                    <li><a class="text-sm text-gray-900 hover:text-gray-500" href="#">Search in offers</a></li>
                    <li class="text-gray-300"></li>
                    <li><a class="text-sm text-gray-900 hover:text-gray-500" href="#">Who We Are</a></li>
                    <li class="text-gray-300"></li>
                    <li><a class="text-sm text-gray-900 hover:text-gray-500 cursor-pointer px-5 py-2" href="#"
                            onclick="toggleSlideover()">Contacts</a></li>
                </ul>

                {% if current_user.is_authenticated %}
                <div class="hidden lg:block relative">
                    <button
                        class="text-white bg-blue-700 hover:bg-blue-800  font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                        onclick="toggleDropdown()">
                        Account
                        <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 10 6">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m1 1 4 4 4-4" />
                        </svg>
                    </button>
                    <div id="dropdownMenu"
                        class="hidden absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg py-2 z-20">
                        <a href="/profile/{{ current_user.id }}"
                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Profile</a>
                        <a href="{{ url_for('auth.log_out') }}"
                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Log Out</a>
                    </div>
                </div>
                {% else %}
                <div class="hidden lg:block">
                    <a class="hidden lg:inline-block bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-1.5 px-4 rounded-xl"
                        href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                    <a class="hidden lg:inline-block py-2 px-4 bg-blue-800 hover:bg-blue-400 text-white font-bold rounded-xl"
                        href="{{ url_for('auth.login') }}">Login</a>
                </div>
                {% endif %}
            </div>

            <div class="navbar-menu hidden z-50">
                <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25 hidden"></div>
                <nav
                    class="fixed top-0 left-0 bottom-0 flex flex-col w-5/6 max-w-sm py-6 px-6 bg-white border-r overflow-y-auto">
                    <div class="flex items-center mb-8 justify-between">
                        <a class="text-3xl font-bold leading-none">
                            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo">
                        </a>
                        <button class="navbar-close">
                            <svg class="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                        </button>
                    </div>
                    <div>
                        <ul>
                            <li class="mb-1">
                                <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded"
                                    href="#">Search in offers</a>
                            </li>
                            <li class="mb-1">
                                <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded"
                                    href="#">Who We Are</a>
                            </li>
                            <li class="mb-1">
                                <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded cursor-pointer px-5 py-2"
                                    href="#" onclick="toggleSlideover()">Contacts</a>
                            </li>
                        </ul>
                    </div>

                    {% if current_user.is_authenticated %}
                    <div class="mt-auto">
                        <div class="pt-6">
                            <a class="block bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 mb-2 text-xs text-center border border-blue-500 hover:border-transparent rounded-xl"
                                href="{{ url_for('auth.log_out') }}">
                                <i class="fas fa-sign-out-alt"></i> Log Out
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="mt-auto">
                        <div class="pt-6">
                            <a class="block bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 mb-2 text-xs text-center border border-blue-500 hover:border-transparent rounded-xl"
                                href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                            <a class="block px-4 py-3 mb-2 leading-loose text-xs text-center text-white font-semibold bg-blue-900 hover:bg-blue-900 rounded-xl"
                                href="{{ url_for('auth.login') }}">Login</a>
                        </div>
                    </div>
                    {% endif %}
                </nav>
            </div>
        </section>
    </nav>




    {% for message in get_flashed_messages() %}
    <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400"
        role="alert">
        <span class="font-medium">{{ message }}</span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20">
                <path
                    d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
            </svg>
        </span>
    </div>
    {% endfor %}

    {% block body %}
    {% endblock %}

    <footer class="relative text-center bg-blue-900 text-white max-w-7xl mx-auto">
        <div class="px-4 py-4 md:py-14 xl:pt-20 xl:pb-12 flex flex-col items-center">
            <img src="{{ url_for('static', filename='images/logo2.png')}}" class="w-32 h-auto mb-9 xl:mb-9">
            <div class="flex space-x-4 items-center">
                <a href="#" class="text-white hover:text-gray-300">
                    <i class="fab fa-facebook-f w-5 h-5"></i>
                </a>
                <a href="#" class="text-white hover:text-gray-300">
                    <i class="fab fa-twitter w-5 h-5"></i>
                </a>
                <a href="#" class="text-white hover:text-gray-300">
                    <i class="fab fa-instagram w-5 h-5"></i>
                </a>
                <a href="#" class="text-white hover:text-gray-300">
                    <i class="fab fa-linkedin-in w-5 h-5"></i>
                </a>
            </div>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='js/script.js')}}"></script>
</body>

</html>

website/templates/forms.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
        referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css')}}">
    <link rel="stylesheet" href="/tailwind.config.js">
    <link rel="stylesheet" href="../static/css/tailwind.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="path/to/your/tailwind.css" rel="stylesheet">
    <title>Real Estate | {% block title %} {% endblock %}</title>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        clifford: '#D6D0D0',
                        navbar: '091638'
                    }
                }
            }
        }
    </script>

</head>

<body>
    {% block body %}
    {% endblock %}

</body>

</html>

website/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<body class="min-h-screen flex items-center justify-center relative bg-gray-50">
    <div class="form-container p-10 md:p-16 rounded-lg bg-white shadow-md">
        <div class="max-w-lg w-full">
            <img src="{{ url_for('static', filename='images/LogoWhite.png') }}" alt="Logo" class="h-10 text-left mb-36">
            <h2 class="text-2xl font-bold mb-5 text-center text-gray-400">
                Or
                <a href="{{ url_for('auth.sign_up') }}" class="hover:underline text-white">Sign Up</a>
            </h2>
            <h2 class="text-2xl font-bold mb-6 text-center text-blue-400">Log In</h2>

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="mb-4">
                {% for category, message in messages %}
                {% if category == 'success' %}
                <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50" role="alert">
                    <span class="font-medium">{{ message }} - Now you can log in.</span>
                </div>
                {% else %}
                <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
                    role="alert">
                    <span class="font-medium">{{ message }}</span>
                    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                        <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20">
                            <path
                                d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
                        </svg>
                    </span>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            {% endwith %}

            <form action="{{ url_for('auth.login') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="mb-1 text-2xl">
                    {{ form.email(class="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none
                    focus:ring focus:ring-blue-500", placeholder="Email") }}
                </div>
                <div class="mb-1">
                    {{ form.password(class="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg
                    focus:outline-none focus:ring focus:ring-blue-500", placeholder="Password") }}
                </div>
                <div class="flex flex-col gap-3 mt-6">
                    {{ form.submit(class="w-full bg-blue-500 text-white py-3 rounded-lg text-sm hover:bg-blue-600
                    focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50") }}
                    <a href="#" class="text-white text-sm hover:underline text-center">Forgot your password?</a>
                    <a href="#" class="text-blue-500 text-sm hover:underline text-center">Log in as <span
                            class="text-white">Admin</span></a>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

website/templates/signup.html
{% extends 'forms.html' %}

{% block title %} Sign Up {% endblock %}

{% block body %}

<body class="font-sans">
    <div class="flex items-center justify-center min-h-screen bg-gray-200 bg-opacity-75">
        <div class="form-container p-6 sm:p-8 md:p-10 lg:p-20 rounded-2xl shadow-lg max-w-md w-full bg-white">
            <img src="{{ url_for('static', filename='images/LogoWhite.png') }}" alt="Logo" class="h-10 text-left mb-36">
            <h2 class="text-2xl font-bold mb-5 text-center text-blue-600">Sign Up</h2>

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="mb-4">
                {% for category, message in messages %}
                <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50" role="alert">
                    <span class="block sm:inline">{{ message }}</span>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endwith %}

            <form method="POST" action="{{ url_for('auth.sign_up') }}">
                {{ form.hidden_tag() }}
                <div class="mb-4">
                    {{ form.first_name(class="w-full p-2 border border-gray-300 rounded-lg", placeholder="First Name")
                    }}
                    {% for error in form.first_name.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-4">
                    {{ form.last_name(class="w-full p-2 border border-gray-300 rounded-lg", placeholder="Last Name") }}
                    {% for error in form.last_name.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-4">
                    {{ form.email(class="w-full p-2 border border-gray-300 rounded-lg", placeholder="Email") }}
                    {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-4">
                    {{ form.password1(class="w-full p-2 border border-gray-300 rounded-lg",
                    placeholder="Enter Your Password") }}
                    {% for error in form.password1.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-4">
                    {{ form.password2(class="w-full p-2 border border-gray-300 rounded-lg",
                    placeholder="Confirm Your Password") }}
                    {% for error in form.password2.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-4">
                    {{ form.submit(class="w-full bg-blue-500 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-600
                    focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50") }}
                </div>
                <div class="text-center">
                    <a href="{{ url_for('auth.login') }}" class="text-gray-700 hover:underline text-xl">Or
                        <span class="text-blue-700">Log In</span>
                    </a>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}